# ~/k3s/projects/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./mariadb
  - ./nextcloud
  - ./privatebin
  - ./storage
  - ./headlamp # NEU hinzugef√ºgt
