# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hedgedoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hedgedoc
  template:
    metadata:
      labels:
        app: hedgedoc
    spec:
      containers:
      - name: hedgedoc
        image: quay.io/hedgedoc/hedgedoc:latest
        ports:
        - containerPort: 3000
        env:
        - name: CMD_DB_URL
          value: "postgres://hedgedoc:hedgedoc@hedgedoc-postgres:5432/hedgedoc?ssl=false"
        - name: CMD_DOMAIN
          value: "notes.druckruck.de"
        - name: CMD_URL_ADDPORT
          value: "true"
        - name: CMD_PROTOCOL_USESSL
          value: "true"
        - name: CMD_SESSION_SECRET
          value: "irgendeinRandomSecret1234"
