apiVersion: apps/v1
kind: Deployment
metadata:
  name: hedgedoc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hedgedoc
  template:
    metadata:
      labels:
        app: hedgedoc
    spec:
      nodeSelector:
        kubernetes.io/arch: "arm64"  # für ARM64, sonst "amd64" für x86
      containers:
        - name: hedgedoc
          image: quay.io/hedgedoc/hedgedoc:latest
          env:
            - name: CMD_DB_URL
              value: postgres://hedgedoc:hedgedocpassword@hedgedoc-postgres:5432/hedgedoc
            - name: CMD_DB_SSL
              value: "false"
            - name: CMD_PROTOCOL_USESSL
              value: "false"
          ports:
            - containerPort: 3000
