# postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hedgedoc-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hedgedoc-postgres
  template:
    metadata:
      labels:
        app: hedgedoc-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: hedgedoc
        - name: POSTGRES_PASSWORD
          value: hedgedoc
        - name: POSTGRES_DB
          value: hedgedoc
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: hedgedoc-pgdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: hedgedoc-pgdata
        persistentVolumeClaim:
          claimName: hedgedoc-pvc
