# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hedgedoc-service
spec:
  selector:
    app: hedgedoc
  ports:
    - protocol: TCP
      port: 80        # Traefik spricht Ã¼ber 80/443
      targetPort: 3000
