apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: projects
  namespace: flux-system
spec:
  interval: 5m
  path: ./projects
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # targetNamespace nur bei einzelnen Ressourcen oder in den manifests setzen, NICHT direkt hier
