apiVersion: apps/v1
kind: Deployment
metadata:
  name: privatebin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privatebin
  template:
    metadata:
      labels:
        app: privatebin
    spec:
      nodeSelector:
        kubernetes.io/arch: "arm64"  # f√ºr ARM64, sonst "amd64"
      containers:
        - name: privatebin
          image: privatebin/nginx-fpm-alpine:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: privatebin-data
              mountPath: /srv/data
      volumes:
        - name: privatebin-data
          emptyDir: {}
