apiVersion: v1
kind: Service
metadata:
  name: privatebin-service
  namespace: default
spec:
  selector:
    app: privatebin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

